### ISSUE TITLE
"Failed to instantiate edge runtime.fig:load:flatten", "__dirname is not defined"

### ISSUE THREAD

**Issue by cheapsteak** [vercel/edge-runtime#225]
## Bug Report

**Current behavior**

Created a blank project to test middleware

<details>
<summary>Server starts up fine</summary>

```
> Success! Build completediming config:load:flatten Completed in 3ms
> Ready! Available at http://localhost:3000
```

</details>

but upon accessing localhost:3000, the page returns "This Edge Function has crashed", and the console logs

```
Failed to instantiate edge runtime.fig:load:flatten Completed in 3ms
__dirname is not defined
```

**Expected behavior/code**

The middleware function to run instead of returning page crash

**Possible solution**

**Additional context/screenshots**
Repro by running `npm run ddev`

[Archive.zip](https://github.com/vercel/edge-runtime/files/10247380/Archive.zip)

I don't believe this is a duplicate of https://github.com/vercel/edge-runtime/issues/209 since I've tried running with node@16.19.0 and also downgrading to a version of vercel cli that was using edge-runtime@1.1.0 and received the same errors

**Comment by cheapsteak** [comment]
looks like I was missing the step of adding `next` as a dependency 🤦 
(I thought I didn't need it since I thought I saw somewhere that middleware and edge functions were framwork agnostic)


apologies for the noise

**Comment by cheapsteak** [comment]
actually sorry this is now working locally but not working when deployed

function logs https://vercel.com/cheapsteak1/lskjdf/DTvY4XUMnwcJoGJU6vkq2rALiNcw/functions showing

```
[GET] /
13:56:48:09
ReferenceError: __dirname is not defined
    at worker.js:21:23819
    at worker.js:21:23861
    at worker.js:14:28
    at worker.js:21:24002
    at worker.js:14:28
    at worker.js:21:24667
    at worker.js:14:28
    at worker.js:21:25045
    at worker.js:14:28
    at worker.js:23:103

[GET] /favicon.ico
13:56:35:43
ReferenceError: __dirname is not defined
    at node_modules/next/dist/compiled/ua-parser-js/ua-parser.js:10:16756
    at node_modules/next/dist/compiled/ua-parser-js/ua-parser.js:10:16885
    at node_modules/next/dist/server/web/spec-extension/user-agent.js:8:41
    at node_modules/next/server.js:6:0
    at middleware.js:4:15
    at middleware:middleware.js:1:17
```

**Comment by Kikobeats** [comment]
Hello, the global [__dirname](https://nodejs.org/docs/latest/api/globals.html#__dirname) is missing at Edge Runtime because it's a Node.js API and the Edge Runtime effort is to cover [WinterCG API](https://github.com/wintercg/proposal-common-minimum-api):

![CleanShot 2023-01-18 at 10 23 27@2x](https://user-images.githubusercontent.com/2096101/213133129-fe403ed9-9022-4940-b88c-3e3db8455a7d.png)

So it's expected to be missing there.

The thing is, if you do the same but using Next.js, `__dirname` exists:

![CleanShot 2023-01-18 at 10 27 24@2x](https://user-images.githubusercontent.com/2096101/213134050-9ba24cbb-2408-4f91-b245-8a5d40e20f97.png)

That's because Next.js is extending Edge Runtime API surface, adding `__dirname` polyfill to be possible to cover more user cases.

**Comment by cheapsteak** [comment]
Thanks for clarifying 🙏 does that mean edge-runtime is only meant to be used with NextJS projects?

**Comment by Kikobeats** [comment]
Not really: You can extend Edge Runtime to add whatever you need:

```js
const { EdgeRuntime } = require('edge-runtime')

const runtime = new EdgeRuntime({
  extend: context => {
    context.__dirname = __dirname
    return context
  }
})

Promise.resolve().then(async () => {
  const result = await runtime.evaluate('__dirname')
  console.log(result)
})
```

Take a look to https://edge-runtime.vercel.app/getting-started#usage 🙂
